fp/admin/routes.py
from flask import Blueprint, render_template, abort, redirect
from flask.helpers import url_for
from flask_login import login_required, current_user
from fp.models import User
from fp import db

admin = Blueprint('admin',__name__)

def administrator(func):
    #checks whether current_user is admin or not, abort 404 if not 
    def wrapper(*args,**kwargs):
        if  current_user.is_admin:
            return func(*args,**kwargs)
        else:
            abort(404)
    # rename wrapper so decorator can work with more than one func
    wrapper.__name__ = func.__name__
    return wrapper

@admin.route('/admin', methods=["GET","POST"])
@login_required
@administrator
def admin_panel():
        users = User.query.all()
        return render_template('admin.html', users = users)

@admin.route('/admin/delete/<int:user_id>')
@login_required
@administrator
def delete_user(user_id):
    user = User.query.filter_by(id=int(user_id)).first()
    if user.username == "admin":
        abort(404)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('admin.admin_panel'))

@admin.route('/admin/makeadmin/<int:user_id>')
@login_required
@administrator
def makeadmin_user(user_id):
    user = User.query.filter_by(id=int(user_id)).first()
    if user.username == "admin" or user.id==current_user.id:
        abort(404)
    flag = not(user.is_admin)
    user.is_admin = flag
    db.session.commit()
    return redirect(url_for('admin.admin_panel'))

fp/main/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for
from fp.main.forms import PostForm
from fp import db



main = Blueprint('main',__name__)

@main.route('/', methods=["GET","POST"])
def index():
    return render_template('index.html')

fp/user/routes.py
from flask import Blueprint, request, render_template, redirect, url_for,current_app
from flask_login import current_user, login_user,  logout_user, login_required
from fp import bcrypt, db
from fp.models import User, Weight
from fp.user.forms import RegisterForm, LoginForm
from fp.user.utils import plot



user = Blueprint('user',__name__)



@user.route('/register', methods=["GET","POST"])
def register():
    form = RegisterForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email=form.email.data,password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('register.html', form=form,title="Register")


@user.route('/login', methods=["GET","POST"])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if  user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=False)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
    return render_template('login.html', form=form)

@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@user.route('/profile')
@login_required
def profile():
    weights = Weight.query.order_by(Weight.weight_date.desc()).filter_by(user_id=current_user.id).all()
    userdate,userweight=[],[]
    for weight in weights:
        userdate.append(weight.weight_date)
        userweight.append(weight.weight)
    result = plot(current_user.id,userdate,userweight)
    path = url_for('static',filename='images/'+ result)
    return render_template('profile.html', weights=weights,url=path)
        

fp/weight/routes.py
from flask import Blueprint, render_template, redirect, url_for,request
from flask_login import login_required, current_user
from fp.weight.forms import WeightForm
from fp import db
from fp.models import Weight
from datetime import  date




weight = Blueprint('weight',__name__)

@weight.route('/', methods=["GET","POST"])
def index():
    #to add: show all users results
    return render_template('index.html')


@weight.route('/add', methods=["GET","POST"])
@login_required
def add():
    form = WeightForm()
    if form.validate_on_submit():

        new_weight = Weight(weight_date=form.weight_date.data,weight=form.weight.data,user_id=current_user.id)
        db.session.add(new_weight)
        db.session.commit()
        return redirect(url_for('user.profile'))
    elif request.method=="GET":
        form.weight_date.data = date.today()
    return render_template('add_weight.html', form=form)

    
@weight.route('/delete/<int:weight_id>')
@login_required
def delete(weight_id):
    weight = Weight.query.filter_by(id=weight_id).first()
    db.session.delete(weight)
    db.session.commit()
    return redirect(url_for('user.profile'))

fp/templates/add_weight.html
{% extends "base.html" %}

{% block content %}

    
    <form method = "POST" action ="">
        {{ form.csrf_token }}
        {{form.weight_date}}
        {{form.weight}}
        {{form.submit()}}
    </form>

{% endblock %}

fp/templates/admin.html
{% extends "base.html" %}

{% block content %}


    {% for user in users %}
        {% if user.username=="admin" %}
            {% continue %}
        {% endif %}
        {% if user.is_admin %}
        <p>{{ user }}, is admin: {{user.is_admin}} </p> <a href="{{url_for('admin.makeadmin_user',user_id = user.id)}}">Unmake admin</a>
        {% else %}
        <p>{{ user }}, is admin: {{user.is_admin}} </p> <a href="{{url_for('admin.makeadmin_user',user_id = user.id)}}">Make admin</a>
        {% endif %}
        <a href="{{url_for('admin.delete_user',user_id = user.id)}}">Delete user</a>

    {% endfor %}


{% endblock %}

fp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Weight App - Track your weight</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{{url_for('main.index')}}">Weight App</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                      <a class="nav-link active" aria-current="page" href="{{url_for('user.profile')}}">Profile</a>
                      {% if current_user.is_authenticated %}
                      <a class="nav-link" href="{{url_for('user.logout')}}">Logout</a>
                        {% if current_user.is_admin %}
                        <a class="nav-link" href="{{url_for('admin.admin_panel')}}">Admin</a>
                        {% endif %}
                      {% else %}
                      <a class="nav-link" href="{{url_for('user.register')}}">Register</a>
                      <a class="nav-link" href="{{url_for('user.login')}}">Login</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </nav>
        </div>
        <div class="row " >
            <div class="col-md-8 my-5">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4 my-5">
              {% if current_user.is_authenticated %}
              <h3 class='text'>{{current_user.username}}</h3>
              {% if current_user.weight%}
              <h6 class='text'>Current weight: {{current_user.weight[-1]}}</h5>
              {% endif %}
                {% if current_user.target%}
                  <h6 class='text'>Target weight: {{current_user.target}}</h5>
                    
                {% endif%}
                <a class="link" href="{{url_for('weight.add')}}">Add weight</a> 
              {% else %}
                <h2 class='text-center'> What is Weight App?</h2>
                <p class='text=center'>Weight app is a free application to track your weight. You can <a class='link' href="{{url_for('user.register')}}">create an account</a>, track your weight on the table and see the chages on the graphic.</p>
                 <a class="link" href="{{url_for('user.login')}}">Login</a> if you already have an account and set some new target!</p>
             {% endif %}
            </div>
        </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

fp/templates/index.html
{% extends "base.html" %}

{% block content %}


<div class="text-center"><h2> Tips To Lose Weight</h2></div>
<h5>1. Do not skip breakfast </h5>
<p>Skipping breakfast will not help you lose weight. </p>
<h5>2. Eat regular meals</h5>
<p>Eating at regular times during the day helps burn calories at a faster rate.</p>
<h5>3. Eat plenty of fruit and veg</h5>
<p>Fruit and veg are low in calories and fat, and high in fibre – 3 essential ingredients for successful weight loss.</p>
<h5>4. Get more active</h5>
<p>Being active is key to losing weight and keeping it off.</p>
<h5>5. Drink plenty of water</h5>
<p>You can end up consuming extra calories when a glass of water is really what you need.</p>

    {% endblock %}

fp/templates/login.html
{% extends "base.html" %}

{% block content %}

    
    <form method = "POST" action ="">
        {{ form.csrf_token }}
        {{form.email}}
        {{form.password}}
        {{form.submit()}}
    </form>

    
{% endblock %}

fp/templates/profile.html
{% extends "base.html" %}

{% block content %}



    <div class="container">
        <div class="row">
    <div class="col-md-6">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Date</th>
            <th scope="col">Weight</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for weight in weights %}
          <tr>
            <th scope="row">{{ weight.id}}</th>
            <td>{{weight.weight_date}} </td>
            <td>{{weight.weight}}</td>
            <td><a href="{{ url_for('weight.delete', weight_id = weight.id) }}">Delete</a></td>
          </tr>
          {% endfor%}
        </tbody>
      </table>
      </div>
      <div class="col-md-6">
        <img src={{url}} alt="Chart" height="auto" width="100%">
      </div>
      </div>
      </div>


{% endblock %}

fp/templates/register.html
{% extends "base.html" %}

{% block content %}

    <form method = "POST" action ="">
        {{ form.csrf_token }}
        Username
        {{form.username}}
        <br>
        Email
        {{form.email}}
        <br>
        Password
        {{form.password}}
        <br>
        Confirm password
        {{form.confirm_password}}
        {{form.submit()}}
    </form>
    
    {% endblock%}